source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JGDialMenu_Example', :exclusive => true do
  pod 'JGDialMenu', :path => '../'
end

target 'JGDialMenu_Tests', :exclusive => true do
  pod 'JGDialMenu', :path => '../'

  
end
